### ISSUE TITLE
Bugs for `Decimal64` initializer

### ISSUE THREAD

**Issue by dehesa** [dirkschreib/Decimal64#2]
The [initializer](https://github.com/dirkschreib/Decimal64/blob/master/Decimal64/Decimal64.swift#L58) transforming a `Double` into a `Decimal64` has two bugs:
- Passing a 0.0 to the initializer crashes the library with the following error:

   ```
   Fatal error: Double value cannot be converted to Int because it is either infinite or NaN
   ```
  
   The bug happens when performing [`log10(0.0)`](https://github.com/dirkschreib/Decimal64/blob/master/Decimal64/Decimal64.swift#L61) (which it is infinite).

- The initializer doesn't return `nil` when `Double` is NaN or Infinitive.

I have already fixed both bugs in my [develop branch](https://github.com/dehesa/Decimal64/tree/develop). You can find the fix [here](https://github.com/dehesa/Decimal64/blob/develop/sources/Decimal64.swift#L617).

**Comment by dehesa** [comment]
The `DecimalFP64` initializer is afflicted by the same bugs. I have also fix those in my develop branch.

**Comment by dirkschreib** [comment]
The bug has been fixed for Decimal64 and a small precision mistake for values < 1 as well.
I'll probably deprecate DecimalFP64 as I have no need for it and a "standard" version should follow  IEEE754-2008.
